import SwiftUI

struct WelcomeView: View {
    @Binding var hasSeenWelcome: Bool
    
    var body: some View {
        VStack(spacing: 0) {
            Spacer()
            
            Image(systemName: "brain.head.profile")
                .font(.system(size: 80))
                .foregroundColor(.teal)
                .padding(.bottom, 24)
                .accessibilityHidden(true)
            
            Text("Welcome to\nCogniGuard")
                .font(.system(.largeTitle, design: .rounded))
                .fontWeight(.bold)
                .multilineTextAlignment(.center)
                .padding(.bottom, 40)
            
            VStack(alignment: .leading, spacing: 24) {
                FeatureRow(icon: "lock.slash.fill", title: "No Spoilers", description: "You won't get ready-made code or direct answers. You have to think.")
                FeatureRow(icon: "lightbulb.fill", title: "Socratic Method", description: "Learn through targeted analogies and guiding questions.")
                FeatureRow(icon: "arrow.up.right.circle.fill", title: "Cognitive Rehab", description: "Break your AI dependency and rebuild your critical thinking.")
            }
            .padding(.horizontal, 32)
            
            Spacer()
            
            Text("Responses are generated by on-device AI and may be inaccurate. Always verify critical information.")
                .font(.caption)
                .foregroundColor(.secondary)
                .multilineTextAlignment(.center)
                .padding(.horizontal, 24)
                .padding(.bottom, 16)
                .accessibilityLabel("Disclaimer: Responses are generated by on-device AI and may be inaccurate. Always verify critical information.")
            
            Button(action: {
                triggerHapticFeedback(style: .heavy)
                withAnimation {
                    hasSeenWelcome = true
                }
            }) {
                Text("Start Calibration")
                    .font(.system(.headline, design: .rounded))
                    .foregroundColor(.white)
                    .frame(maxWidth: .infinity)
                    .padding()
                    .background(Color.teal)
                    .cornerRadius(16)
            }
            .padding(.horizontal, 24)
            .padding(.bottom, 40)
            .accessibilityLabel("Start Calibration Button")
        }
        .background(Color(uiColor: .systemGroupedBackground).ignoresSafeArea())
    }
}
